[default]
output_file_name = "example_file.csv"

[local]
    [local.snowflake]
    user = "${SNOWFLAKE_USERNAME}"
    password = "${SNOWFLAKE_PASSWORD}"
    account = "exampleaccount"
    region = "us-east-1"
    database = "MY_DATABASE"
    role = "MY_ROLE"
    warehouse = "MY_WH"

    [local.sftp]
    host = "ftp.example.com"
    port = 22
    username = "ExampleUser"
    host_fingerprint = ""
    private_key = "${SFTP_PRIVATE_KEY}"
    passphrase = "${SFTP_PRIVATE_KEY_PASSPHRASE}"
    directory = "Inbox"
    download_dir = "./"

    [local.slack]
    app_name = "Example Recipe"
    api_token = "ssm:/etl/slack-api-token"
    channel_id = "X1234YZA108"
    enabled = false

[sbx]


[prd]

